// Interfaccia
const govSel=v=>`<select id="ng">${GOV.map((g,i)=>`<option value="${i}" ${i===v?"selected":""}>${esc(g[0])} — oro ${g[1]}, pop. ${g[2]}</option>`).join("")}</select>`;
function modalH(){if(!S.modal)return"";const ty=S.modal.type;if(ty==="player")return playerH(S.modal.id);if(ty==="trade")return tradeModalH();if(ty==="inbox")return inboxH();
 const ed=S.modal.type==="edit",p=P()||{};
 return `<div class="modal"><div><h2>${ed?"Modifica nazione":"Crea la tua Nazione"}</h2><input id="nn" maxlength="${MAXN}" placeholder="Nome (max ${MAXN} caratteri)" value="${esc(ed?p.nation:"")}">${govSel(ed?p.gov:0)}${ed?"":`<p class="m">Bonus: ${START} oro (5 quadrati). Il quadrato scelto sarà la Capitale.</p>`}<div class="row"><button class="g" onclick="S.modal=null;draw()">Annulla</button><button onclick="${ed?"saveNation()":"createNation()"}">${ed?"Salva":"Fondala"}</button></div></div></div>`}
async function tileClick(i){if(S.room.status!=="playing"||!isL[i])return;const p=P(),t=S.tiles[i];
 if(!p||!p.nation){if(t.owner){S.msg="Scegli un quadrato libero";return draw()}S.modal={type:"new",tile:i};return draw()}
 if(S.atk!=null&&t.owner!==uid){
  if(t.owner&&!atWar(uid,t.owner)){S.atk=null;S.msg=sameConf(uid,t.owner)||isAlly(uid,t.owner)?"Non puoi attaccare un alleato o un confederato":"Non sei in guerra con "+nm(t.owner)+": dichiaragli guerra da qui";S.modal={type:"player",id:t.owner};return draw()}
  const f=S.atk;S.atk=null;S.msg="";await sendAtk(f,i);return}
 if(t.owner&&t.owner!==uid){S.sel=null;S.atk=null;S.msg="";S.modal={type:"player",id:t.owner};return draw()} // tocchi un altro giocatore: menu diplomatico
 S.sel=i;S.atk=null;draw()}
function tileP(i,p){const t=S.tiles[i],tr=t.troops||{};let h=`<div class="card"><b>Quadrato ${i+1}</b> ${RESMAP[i]?RI[RESMAP[i]]+" "+RN[RESMAP[i]]:""} — ${t.owner?esc(nm(t.owner)):"libero"}<br>`;
 if(t.owner===uid){h+=`<div class="m">Guarnigione: ${Object.entries(UN).map(([k,u])=>u.n+" "+(tr[k]||0)).join(" · ")}</div><div class="row">${Object.entries(UN).map(([k,u])=>`<button class="g" onclick="recruit(${i},'${k}')">+${u.n} (${u.g}💰${Object.entries(u.r).map(([a,b])=>" "+b+RI[a]).join("")} ${u.pop}👥)</button>`).join("")}</div><div class="row">`+
  (t.factory?"":`<button onclick="factory(${i})">Fabbrica (100💰 2🔩)</button>`)+(cnt(tr)?`<button onclick="S.atk=${i};S.msg='Tocca il quadrato da attaccare';draw()">⚔️ Attacca</button>`:"")+(p.capital!==i?`<button class="g" onclick="setCap(${i})">Imposta capitale</button>`:"<span class='m'>Capitale</span>")+"</div>"}
 else if(!t.owner)h+=`<button onclick="buy(${i})">Acquista per ${BASE} oro</button>`;
 else h+=`<span class="m">Si acquista solo tramite commercio, o conquista con le truppe.</span>`;
 return h+"</div>"}
const topH=p=>{const r=p.res||{},n=inbox().length;
 return `<div class="top"><span class="st"><small>Soldi</small><b>💰 ${Math.floor(p.gold||0)}</b></span><span class="st"><small>Manodopera</small><b>👥 ${p.pop||0}</b></span><span class="sm">🔩${r.fe||0} 🌲${r.le||0} ⚫${r.ca||0}<br>📈+${Math.round(share())}/turno · ⏱<span id="tm">${S.left}s</span></span>${n?`<button class="inb pulse" onclick="S.msg='';S.modal={type:'inbox'};draw()">📨 ${n}</button>`:""}</div>`};
const botH=p=>`<div class="bot"><span>🏛️ ${esc(GOV[p.gov][0])}</span><button onclick="S.modal={type:'edit'};draw()">Modifica governo</button></div><div style="height:72px"></div>`;
function nationsH(){const o=others();if(!o.length)return""; // diplomazia: esiste solo se c'è almeno un altro giocatore
 return `<div class="card"><h2>Nazioni</h2><div class="row">${o.map(id=>{const ic=atWar(uid,id)?"⚔️ ":sameConf(uid,id)?"🏛️ ":isAlly(uid,id)?"🤝 ":"";return `<button class="g" style="flex:none;border-left:6px solid ${col(id)}" onclick="S.msg='';S.modal={type:'player',id:'${id}'};draw()">${ic}${esc(nm(id))}</button>`}).join("")}</div><div class="m">Tocca una nazione (o un suo quadrato sulla mappa) per guerra, alleanza, confederazione o scambio.</div></div>`}
function draw(){
 const keep=document.activeElement?.id,kv=document.activeElement?.value,p=P()||{};let h=`<h1>🗺️ Griglia 4x4</h1>`;
 if(S.view==="login"){h+=`<div class="card"><h2>Accesso</h2><p class="m">La sessione resta attiva su questo dispositivo (account anonimo Firebase). I dati locali sono cifrati (AES-GCM).</p><input id="un" maxlength="30" placeholder="Scegli un nome utente" value="${esc(S.profile?.username)}"><button style="width:100%" onclick="saveProfile()">Entra</button></div>`}
 if(S.view==="menu")h+=`<div class="card"><p>👤 ${esc(S.profile?.username)}</p><button onclick="S.view='lobby';draw()" style="width:100%">Gioca</button><br><br><button class="g" style="width:100%" onclick="S.view='set';draw()">Impostazioni</button></div>`;
 if(S.view==="set")h+=`<div class="card"><h2>Impostazioni</h2><button class="g" onclick="document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark'">Tema</button> <button class="g" onclick="logout()">Cambia nome</button> <button class="g" onclick="S.view='menu';draw()">Indietro</button></div>`;
 if(S.view==="lobby"){const pub=S.list.filter(r=>r.public);h+=`<div class="card"><h2>Crea stanza</h2><input id="rn" placeholder="Nome stanza"><select id="rp"><option value="1">Pubblica</option><option value="0">Privata (codice)</option></select><button onclick="createRoom()" style="width:100%">Crea</button></div><div class="card"><h2>Unisciti con codice</h2><div class="row"><input id="jc" placeholder="Codice" maxlength="5"><button onclick="joinRoom(document.getElementById('jc').value)">Entra</button></div></div><div class="card"><h2>Stanze pubbliche</h2>${pub.length?pub.map(r=>`<div class="row"><span>${esc(r.name)} <span class="m">${esc(r.id)}</span></span><button onclick="joinRoom('${esc(r.id)}')">Entra</button></div>`).join(""):'<p class="m">Nessuna stanza.</p>'}</div><p class="m">${esc(S.msg)}</p><button class="g" onclick="S.view='menu';draw()">Indietro</button>`}
 if(S.view==="room"&&S.room){const ids=Object.keys(S.players);if(S.room.status!=="lobby"&&p.nation)h+=topH(p);h+=`<div class="card"><b>${esc(S.room.name)}</b> <span class="m">codice ${esc(S.code)} · ${ids.length}/16</span>`;
  if(S.room.status==="lobby")h+=`<h2>Lobby</h2>${ids.map(id=>`<div>👤 ${esc(S.players[id].user||"?")}${id===uid?" (tu)":""} — ${S.players[id].ready?"✅ Pronto":"⏳ In attesa"}</div>`).join("")}<h2>Anteprima</h2><div class="grid" style="grid-template-columns:repeat(${W},var(--cs,18px))">${S.tiles.map((_,i)=>!isL[i]?WAT:`<div class="t b${BIO[i]}" style="cursor:default">${RESMAP[i]?RI[RESMAP[i]]:""}</div>`).join("")}</div><div class="row"><button onclick="ready()">${p.ready?"Annulla pronto":"Pronto"}</button>${S.room.host===uid?`<button onclick="start()" ${ids.every(i=>S.players[i].ready)?"":"disabled"}>Avvia</button>`:""}</div>`;
  else{h+=`${p.nation?`<div class="m">🏳️ ${esc(p.nation)}</div>`:'<div class="m">Clicca un quadrato libero per fondare la nazione.</div>'}
   <div class="row"><button class="g" onclick="zoom(-3)">➖</button><button class="g" onclick="zoom(3)">➕</button><span class="m">rotella = zoom · trascina = sposta</span></div><div class="grid" style="grid-template-columns:repeat(${W},var(--cs,18px))">${S.tiles.map((t,i)=>{if(!isL[i])return WAT;const c=t.owner?col(t.owner):"",a=S.atks.find(x=>x.to===i),n=cnt(t.troops);return `<div class="t b${BIO[i]} ${S.sel===i?"sel":""}" onclick="tileClick(${i})" style="${c?`background-image:linear-gradient(${c}b0,${c}b0);border-color:${c}`:""}"><span>${RESMAP[i]?RI[RESMAP[i]]:""}${S.players[t.owner]?.capital===i?"🏛️":""}${t.factory?"🏭":""}${n?"🗡️"+n:""}</span>${a?`<b>⚔️${Math.max(0,Math.ceil((a.end-Date.now())/1000))}s</b>`:""}</div>`}).join("")}</div>`;
   if(S.sel!=null&&p.nation)h+=tileP(S.sel,p);if(p.nation)h+=nationsH();h+=`<div class="m">${esc(S.msg)}</div>`}
  h+=`<br><button class="g" onclick="leave()">Esci dalla stanza</button></div>`;if(S.room.status!=="lobby"&&p.nation)h+=botH(p)}
 const gs=document.querySelector(".grid"),sx=gs?.scrollLeft||0,sy=gs?.scrollTop||0;$.innerHTML=h+modalH();const g2=document.querySelector(".grid");if(g2){g2.scrollLeft=sx;g2.scrollTop=sy}
 if(keep){const e=document.getElementById(keep);if(e&&kv!=null){e.value=kv;e.focus()}}}
